# Generated by Django 5.0 on 2023-12-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('espécie', models.CharField(max_length=100)),
                ('raça', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('descrição', models.CharField(max_length=200)),
                ('tamanho', models.CharField(max_length=100)),
            ],
        ),
    ]
