# Generated by Django 5.0 on 2023-12-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animais',
            options={'verbose_name': 'Animai'},
        ),
        migrations.RemoveField(
            model_name='animais',
            name='espécie',
        ),
        migrations.AddField(
            model_name='animais',
            name='Cachorro',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='animais',
            name='Gato',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='animais',
            name='descrição',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
