# Generated by Django 5.0 on 2023-12-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_alter_animais_options_remove_animais_espécie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animais',
            options={},
        ),
    ]
