# Generated by Django 5.0 on 2023-12-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_alter_animais_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img_pets'),
        ),
    ]
